#!/usr/bin/env ruby
# Copyright 2016 DAQRI LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Example config file and script for creating a security group.
# AWS credentials should be in environment variables AWS_ACCESS_KEY_ID and
# AWS_SECRET_ACCESS_KEY

require_relative './sg_helpers.rb'

ssh_ips = ["209.49.4.10/32", "78.137.139.14/32", "54.212.254.142/32"]
https_ips = ["10.8.0.0/16", "208.184.77.122/32", "209.49.4.10/32"]
icmp_ips = ["10.8.0.0/16", "78.137.139.14/32", "209.49.4.10/32"]

example_group = {'group_name' => 'example group',
                 'group_description' => 'The quick brown fox jumped over the lazy dog.',
                 'vpc_id' => 'vpc-011e8c64',
                 'region' => 'us-west-2',
                 'permissions' => [{'ips' => ssh_ips,
                                    'from_port' => 22,
                                    'to_port' => 22,
                                    'protocol' => 'tcp'},
                                   {'ips' => https_ips,
                                    'from_port' => 443,
                                    'to_port' => 443,
                                    'protocol' => 'tcp'},
                                   {'ips' => icmp_ips,
                                    'from_port' => -1,
                                    'to_port' => -1,
                                    'protocol' => 'icmp'}]}

sg_create(example_group)

# The following calls can be made on a pre-existing group
# sg_audit(example_group)
# sg_update(example_group)
